-- Update AVG_HARGA_BELI_PIECES berdasarkan weighted average dari semua pemesanan
-- Formula: AVG_HARGA_BELI_PIECES = SUM(HARGA_PESAN_BARANG_DUS * TOTAL_MASUK_DUS) / SUM(TOTAL_MASUK_DUS * SATUAN_PERDUS)
UPDATE MASTER_BARANG 
SET AVG_HARGA_BELI_PIECES = 29899.04
WHERE KD_BARANG = 'W8r1LuGwd932W3Zq';

-- Verifikasi
SELECT KD_BARANG, NAMA_BARANG, AVG_HARGA_BELI_PIECES, SATUAN_PERDUS
FROM MASTER_BARANG
WHERE KD_BARANG = 'W8r1LuGwd932W3Zq';
